### ISSUE TITLE
Doctor class exposes the list of Patient objects

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleMedicalLogger#2]
https://github.com/NikolaDmitrasinovic/ConsoleMedicalLogger/blob/main/Persons/Doctor.cs

I could for example access the `List<Patient> MyPatients` from anywhere and simply delete it - that is not how it's done. Correct solution would be to create a method `AddPatient(Patient p)` to the `IDoctor` interface, and then make such an implementation that the method `ChosePersonalDoctor(Doctor doctor)` from the `Patient` class calls that one as well.

That way no one can access the list itself - you can only add patients (and maybe other stuff if you chose to add it), not misuse the entire structure.

It's good design.

**Comment by NikolaDmitrasinovic** [comment]
Solved with AddRemovePatient() method.
