### ISSUE TITLE
Assignment expansion - automatic doctor assignment

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleMedicalLogger#6]
Let's expand the assignment.

Imagine this: you create a patient and you can assign him a doctor upon creation (we do not allow patients to be without doctors). Now, if no doctor is forwarded in the constructor (obviously, that's two constructors) we award him one of the randomly chosen doctors that are currently free.

Every doctor now should have a limit as to how many patients he can take in - if he is maxed out then he will not be eligible to be selected. How you can keep track of current and maximum patient count for each doctor - that is obvious. Think about how you could keep tabs on all available doctors we have at the moment, and then how would we choose a random one among those who are free.

Anything that isn't fully defined can be implemented arbitrarily.

**Comment by NikolaDmitrasinovic** [comment]
This one is done.
