### ISSUE TITLE
Test Linq filtering

### ISSUE THREAD

**Issue by NikolaVetnic** [NikolaDmitrasinovic/ConsoleMedicalLogger#7]
This line i `Patient` class is suspicious:
```C#
MyExams = MyExams.Where(ex => ex.done == true).ToList();
```

Would it not actually only leave the DONE exams in, and filter out those that are NOT DONE? In case there are problems understanding Linq, use traditional loops and copies of lists, no shame in that.

**Comment by NikolaDmitrasinovic** [comment]
That was leftover from trying to fix different issue, Linq query now written the right way.
